# Generated by Django 6.0.4 on 2026-04-28 11:03

import django.db.models.deletion
from django.db import migrations, models


def create_categories_from_strings(apps, schema_editor):
    """Create Category objects from the string values in events"""
    Event = apps.get_model("planner", "Event")
    Category = apps.get_model("planner", "Category")

    # Get all unique users and categories using ORM (raw() must include PK)
    for row in Event.objects.values("user_id", "category").distinct():
        try:
            cat_string = row.get("category")
            user_id = row.get("user_id")
            if cat_string:
                Category.objects.get_or_create(
                    user_id=user_id, name=cat_string, defaults={"color": "#0d9488"}
                )
        except Exception:
            # Avoid migration failure on unexpected data issues
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#0d9488", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RunPython(create_categories_from_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planner.category",
            ),
        ),
    ]
