# Generated by Django 6.0.4 on 2026-04-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_category_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rrule',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('override_title', models.CharField(blank=True, max_length=150, null=True)),
                ('override_description', models.TextField(blank=True, null=True)),
                ('override_start_time', models.DateTimeField(blank=True, null=True)),
                ('override_end_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='planner.event')),
            ],
            options={
                'unique_together': {('event', 'original_start')},
            },
        ),
    ]
